### ISSUE TITLE
YAML

### ISSUE THREAD

**Issue by godtaehee** [godtaehee/Swagger#3]
### YAML
**YAML** is a structured data format that the Open API Specification format uses

To create an API definition file, you can use one of two structured data formats: YAML or JSON.

**YAML** stands for YAML Ain't Markup Language.

It's used for data not for content

### Lists
```yaml
cart:
  - part_no: ABCD
    description: Photoresistor
    price: 1.47
    quantity: 4
    
  - part_no: B3443
    description: LED
    color: blue
    price: 0.29
    quantity: 12
```

There's an element named "cart", and it's a list with two items in it.

You just need to put a dash in front of a key/value pair and a list item, and then YAML knows it's a list.

### Multi-line strings
- Because there are no quotation marks on strings, you need special characters for multiline strings
- `|` character means preserve lines and spaces
- `>` character is used to fold everything into one line regardless of line breaks, just like HTML. Like HTML, a blank line indicates a new paragraph.
![스크린샷 2021-08-05 오전 11 13 20](https://user-images.githubusercontent.com/44861205/128280096-d909bf4b-be1e-478d-8eef-cc2c01469136.png)
-  there are variations -- there's like |- and |+

### Comments
Use `#`

### Schema
Although not officially part of YAML, OAS uses references for schemas.

These schemas are used to describe the request and response bodies.

The main thing to note now is that you'd use $ref to indicate a reference. Then you typically put the schema in a definition section.
![스크린샷 2021-08-05 오전 11 21 37](https://user-images.githubusercontent.com/44861205/128280803-23ea3243-26bc-4c4a-a00e-681aab5a73f7.png)
